"""
Build-integrity tests: the build runs, the embedded data is well-formed, and
card IDs are unique and stable (IDs are the localStorage keys for user progress,
so a silent rename would wipe someone's schedule).
"""

import re
import subprocess
import sys

import pytest

from conftest import extract_decks, DATA_DIR


CARD_KEYS = {"id", "front", "frontSub", "frontLabel", "back", "backSub", "notes"}


def test_build_succeeds_and_reports_stats(built):
    assert "Total decks:" in built.stdout
    assert "App written to" in built.stdout


def test_decks_nonempty(decks):
    assert isinstance(decks, list) and len(decks) > 0
    assert all(isinstance(d.get("cards"), list) for d in decks)


def test_every_card_has_full_shape(all_cards):
    assert all_cards, "no cards generated"
    for c in all_cards:
        missing = CARD_KEYS - set(c.keys())
        assert not missing, f"card {c.get('id')} missing keys {missing}"
        assert c["id"], "card with empty id"
        assert c["front"] != "", f"card {c['id']} has empty front"
        assert c["back"] != "", f"card {c['id']} has empty back"


def test_all_card_ids_globally_unique(all_cards):
    ids = [c["id"] for c in all_cards]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    assert not dupes, f"duplicate card ids across decks: {dupes}"


def test_card_ids_have_no_whitespace(all_cards):
    bad = [c["id"] for c in all_cards if re.search(r"\s", c["id"])]
    assert not bad, f"card ids contain whitespace: {bad}"


def test_autogenerated_id_prefixes(decks):
    """Auto-generated id families follow the documented prefixes.

    (Vocabulary cards use manually-assigned ids in their JSON, so they are
    intentionally not constrained here — only uniqueness/whitespace apply.)
    """
    offenders = []
    for d in decks:
        for c in d["cards"]:
            cid, did = c["id"], d["id"]
            if d.get("type") == "conjugation":
                if did.startswith("verb_conj") and not cid.startswith("vconj_"):
                    offenders.append((did, cid))
                if did.startswith("adj_conj") and not cid.startswith("adjconj_"):
                    offenders.append((did, cid))
            elif did == "verb_vocab" and not cid.startswith("vvoc_"):
                offenders.append((did, cid))
            elif did in ("adj_i", "adj_na") and not cid.startswith("adj_"):
                offenders.append((did, cid))
    assert not offenders, f"auto-generated cards with wrong id prefixes: {offenders[:10]}"


def test_known_ids_present_for_stability(all_cards):
    """IDs that must never change — a silent rename destroys user progress."""
    ids = {c["id"] for c in all_cards}
    for sid in [
        "adjconj_i_いい___よい_neg_cas",
        "adjconj_i_あたまがいい_neg_cas",
        "adjconj_i_なかがいい_negpast_cas",
        "adjconj_i_かわいい_neg_cas",
    ]:
        assert sid in ids, f"expected stable id missing (progress-breaking): {sid}"


def test_recap_deck_count_matches_files(decks):
    n_files = len(list(DATA_DIR.glob("weekly_recap_*.json")))
    n_recap_decks = sum(1 for d in decks if d.get("type") == "recap")
    assert n_recap_decks == n_files, (
        f"{n_recap_decks} recap decks but {n_files} recap files"
    )


def test_expected_deck_families_present(decks):
    ids = {d["id"] for d in decks}
    for needed in [
        "adj_conj_i_neg_cas",
        "adj_conj_i_past_cas",
        "adj_conj_i_negpast_cas",
        "adj_conj_na_neg_pol",
        "verb_conj_masu",
        "verb_vocab",
    ]:
        assert needed in ids, f"missing expected deck {needed}"


def test_build_is_deterministic(built):
    """Re-running the build must produce byte-identical output."""
    proc = subprocess.run(
        [sys.executable, "build_app.py"],
        cwd=built.study_app,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0
    rebuilt = (built.study_app / "index.html").read_text(encoding="utf-8")
    assert rebuilt == built.html, "build output is not deterministic"
    # and the decks survive a second extraction
    assert extract_decks(rebuilt) == built.decks
