"""
Build-integrity tests: the build runs, the embedded data is well-formed, and
card IDs are unique and stable (IDs are the localStorage keys for user progress,
so a silent rename would wipe someone's schedule).
"""

import re
import subprocess
import sys

import pytest

from conftest import extract_decks, DATA_DIR


CARD_KEYS = {"id", "front", "frontSub", "frontLabel", "back", "backSub", "notes"}


def test_build_succeeds_and_reports_stats(built):
    assert "Total decks:" in built.stdout
    assert "App written to" in built.stdout


def test_decks_nonempty(decks):
    assert isinstance(decks, list) and len(decks) > 0
    assert all(isinstance(d.get("cards"), list) for d in decks)


def test_every_card_has_full_shape(all_cards):
    assert all_cards, "no cards generated"
    for c in all_cards:
        missing = CARD_KEYS - set(c.keys())
        assert not missing, f"card {c.get('id')} missing keys {missing}"
        assert c["id"], "card with empty id"
        assert c["front"] != "", f"card {c['id']} has empty front"
        assert c["back"] != "", f"card {c['id']} has empty back"


def test_all_card_ids_globally_unique(all_cards):
    ids = [c["id"] for c in all_cards]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    assert not dupes, f"duplicate card ids across decks: {dupes}"


def test_card_ids_have_no_whitespace(all_cards):
    bad = [c["id"] for c in all_cards if re.search(r"\s", c["id"])]
    assert not bad, f"card ids contain whitespace: {bad}"


def test_autogenerated_id_prefixes(decks):
    """Auto-generated id families follow the documented prefixes.

    (Vocabulary cards use manually-assigned ids in their JSON, so they are
    intentionally not constrained here — only uniqueness/whitespace apply.)
    """
    offenders = []
    for d in decks:
        for c in d["cards"]:
            cid, did = c["id"], d["id"]
            if did == "conj_drills_verbs":
                if not cid.startswith("vconj_"):
                    offenders.append((did, cid))
            elif did == "conj_drills_adj":
                if not cid.startswith("adjconj_"):
                    offenders.append((did, cid))
            elif did.startswith("conj_patterns_"):
                if not cid.startswith("concept_"):
                    offenders.append((did, cid))
            elif did == "verb_vocab":
                if not cid.startswith("vvoc_"):
                    offenders.append((did, cid))
            elif did in ("adj_i", "adj_na"):
                if not cid.startswith("adj_"):
                    offenders.append((did, cid))
    assert not offenders, f"auto-generated cards with wrong id prefixes: {offenders[:10]}"


def test_known_ids_present_for_stability(all_cards):
    """IDs that must never change — a silent rename destroys user progress."""
    ids = {c["id"] for c in all_cards}
    for sid in [
        "adjconj_i_いい___よい_neg_cas",
        "adjconj_i_あたまがいい_neg_cas",
        "adjconj_i_なかがいい_negpast_cas",
        "adjconj_i_かわいい_neg_cas",
    ]:
        assert sid in ids, f"expected stable id missing (progress-breaking): {sid}"


def test_latest_recap_present(decks):
    r = next((d for d in decks if d["id"] == "recap_2026_06_18"), None)
    assert r is not None, "June 18 recap deck missing"
    assert r["type"] == "recap"
    assert len(r["cards"]) >= 15
    assert r.get("topics"), "recap should list topics_covered"
    assert len(r.get("summary", [])) >= 1, "recap should include a concept summary"


def test_concept_decks_have_summaries(decks):
    """Conjugation + counting + recap decks carry a structured concept summary."""
    for did in ("conj_drills_verbs", "conj_drills_adj", "counting", "recap_2026_06_18"):
        d = next(x for x in decks if x["id"] == did)
        summ = d.get("summary", [])
        assert summ, f"{did} should have a concept summary"
        for sec in summ:
            assert sec.get("h"), f"{did} summary section missing a heading"
            assert sec.get("items"), f"{did} summary section missing items"
            assert all(isinstance(i, str) and i for i in sec["items"])


def test_plain_vocab_decks_have_no_summary(decks):
    """Per request: summaries are for concept decks, not plain vocab."""
    for did in ("family", "countries", "occupations"):
        d = next(x for x in decks if x["id"] == did)
        assert not d.get("summary"), f"{did} should not carry a summary"


def test_recap_deck_count_matches_files(decks):
    n_files = len(list(DATA_DIR.glob("weekly_recap_*.json")))
    n_recap_decks = sum(1 for d in decks if d.get("type") == "recap")
    assert n_recap_decks == n_files, (
        f"{n_recap_decks} recap decks but {n_files} recap files"
    )


def test_expected_deck_families_present(decks):
    ids = {d["id"] for d in decks}
    for needed in [
        "conj_drills_verbs", "conj_drills_adj",
        "conj_patterns_verbs", "conj_patterns_adj",
        "verb_vocab", "adj_i", "adj_na", "counting",
    ]:
        assert needed in ids, f"missing expected deck {needed}"


def test_verb_and_adjective_drills_are_separated(decks):
    """Class feedback: verbs and adjectives get their own decks."""
    verb = next((d for d in decks if d["id"] == "conj_drills_verbs"), None)
    adj = next((d for d in decks if d["id"] == "conj_drills_adj"), None)
    assert verb and adj, "expected separate verb and adjective drill decks"
    assert all(c["id"].startswith("vconj_") for c in verb["cards"]), "verb deck has non-verb cards"
    assert all(c["id"].startswith("adjconj_") for c in adj["cards"]), "adj deck has non-adjective cards"
    # the old combined / per-form decks must be gone
    assert not any(d["id"] in ("conj_drills", "conj_patterns") for d in decks)
    stale = [d["id"] for d in decks if d["id"].startswith(("verb_conj", "adj_conj_"))]
    assert not stale, f"stale split decks: {stale}"


def test_english_meaning_on_back_of_drills(decks):
    """The user's request: prompt stays on front, English meaning moves to back."""
    for did in ("conj_drills_verbs", "conj_drills_adj"):
        d = next(x for x in decks if x["id"] == did)
        for c in d["cards"]:
            assert c["frontLabel"], f"{c['id']} lost its prompt"
            assert c["frontSub"] == "", f"{c['id']} still shows English on the front"
            assert c["backSub"], f"{c['id']} missing English meaning on the back"


def test_patterns_decks_present_and_shaped(decks):
    for did in ("conj_patterns_verbs", "conj_patterns_adj"):
        d = next((x for x in decks if x["id"] == did), None)
        assert d is not None, f"missing patterns deck {did}"
        assert len(d["cards"]) >= 5
        for c in d["cards"]:
            assert c["id"].startswith("concept_"), f"unexpected concept id {c['id']}"
            assert c["front"] and c["back"], f"{c['id']} missing front/back"


def test_counting_deck_present_with_key_readings(decks):
    d = next((x for x in decks if x["id"] == "counting"), None)
    assert d is not None, "Counting deck missing"
    assert d["type"] == "vocab"
    assert len(d["cards"]) >= 60
    fronts = {c["front"] for c in d["cards"]}
    # irregular readings & sound changes that must have made it in
    for reading in ["ひとり", "ふたり", "よにん", "はたち", "さんがい",
                    "いっぽん", "さんぼん", "ろっぴき", "さんびき", "いくつ"]:
        assert reading in fronts, f"counting deck missing key reading {reading}"


def test_build_is_deterministic(built):
    """Re-running the build must produce byte-identical output."""
    proc = subprocess.run(
        [sys.executable, "build_app.py"],
        cwd=built.study_app,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0
    rebuilt = (built.study_app / "index.html").read_text(encoding="utf-8")
    assert rebuilt == built.html, "build output is not deterministic"
    # and the decks survive a second extraction
    assert extract_decks(rebuilt) == built.decks
